#ansible-playbook test-playbook.yml --extra-vars "ansible_become_pass=sudo_pass"
#To run without installing software dependencies
#ansible-playbook test-playbook.yml --extra-vars "ansible_become_pass=sudo_pass" --skip-tags "software"
- hosts: localhost

  pre_tasks:
     - raw:  ansible-galaxy role install -r requirements.yml

  vars:
    bitbucket_create_repo:
      1:
        repo_name: "helm-test-role"
        workspace: "{{ bitbucket_workspace }}"
        project: GITH
        is_private: true
        scm: git

  tasks:
    - name: Including role to test
      include_role:
        name: '../common_github-create-repo'
